cookie:
  expiry_days: 0
  key: launch-darkly-test-app-key
  name: launch-darkly-test-app
credentials:
  usernames:
    brian:
      email: brian@example.com
      failed_login_attempts: 0
      first_name: Brian
      gender: Male
      id: 664c0b25-cf50-44c9-bf80-4dcf7fe789b9
      last_name: Roepke
      logged_in: true
      password: $2b$12$FuuMLiF/SRtknvoOPPQLVe0uqo/dirugnpOKkyPmGmlB.hWO17oKK
      roles:
      - admin
      - editor
      - viewer
    chris:
      email: chris@example.com
      failed_login_attempts: 0
      first_name: Chris
      gender: Felmale
      id: 9d890182-87b1-412b-8138-eee1aea8b691
      last_name: Anderson
      logged_in: false
      password: $2b$12$6B/QYpyiHmh.GhSPORFfHeKXduO7nSSb5FWxqlN4I6Ccl.rR8jFBO
      roles:
      - admin
      - editor
      - viewer
