cookie:
  expiry_days: 0
  key: launch-darkly-test-app-key
  name: launch-darkly-test-app
credentials:
  usernames:
    andrew:
      email: andrew@example.com
      failed_login_attempts: 0
      first_name: Andrew
      gender: Male
      id: a15a8384-2dbc-4221-80a9-2100850d9d6d
      last_name: Mack
      logged_in: true
      password: $2b$12$lMvzMq0wGK6xaWVBawg7Wuk/ShIgSsRwEF1kaVhIIe9VXNuQ3Oi4q
    brian:
      email: brian@example.com
      failed_login_attempts: 0
      first_name: Brian
      gender: Male
      id: 664c0b25-cf50-44c9-bf80-4dcf7fe789b9
      last_name: Roepke
      logged_in: false
      password: $2b$12$FuuMLiF/SRtknvoOPPQLVe0uqo/dirugnpOKkyPmGmlB.hWO17oKK
    chris:
      email: chris@example.com
      failed_login_attempts: 0
      first_name: Chris
      gender: Female
      id: 9d890182-87b1-412b-8138-eee1aea8b691
      last_name: Anderson
      logged_in: false
      password: $2b$12$6B/QYpyiHmh.GhSPORFfHeKXduO7nSSb5FWxqlN4I6Ccl.rR8jFBO
    eric:
      email: eric@example.com
      failed_login_attempts: 0
      first_name: Eric
      gender: Male
      id: 9333ad76-153f-409b-aa58-d66dacc74f5c
      last_name: Johnson
      logged_in: true
      password: $2b$12$BtsYDznRSlUulACwdWeP2uEJCVi8nE1kVtRwfpUr86btMwwnpi4zC
